default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  username: <%= ENV["DB_USER"] || "kaku_tail" %>
  password: <%= ENV["DB_PASS"] || "kaku_tail" %>
  host:     <%= ENV["DB_HOST"] || "localhost" %>
  port:     <%= ENV["DB_PORT"] || 5432 %>
  timeout: 5000

development:
  <<: *default
  database: kaku_tail_uploader_development

test:
  <<: *default
  database: kaku_tail_uploader_test

production:
  <<: *default
  database: kaku_tail_uploader_production
  host:     <%= ENV["DB_HOST"] %>
  password: <%= ENV["DB_PASS"] %>
